---
# 🟢 PARTIE EXTRACT

### Ex E1 ⭐ — Explorer les sources
Affichez pour chaque DataFrame : shape, colonnes, dtypes, et les 3 premières lignes.

In [2463]:
# TON CODE ICI
import pandas as pd
df_clients = pd.read_csv("data/clients.csv")
df_commandes_q1 = pd.read_csv("data/commandes_Q1.csv")
df_commandes_q2 = pd.read_csv("data/commandes_Q2.csv")
df_produits = pd.read_csv("data/produits.csv")

display(df_commandes_q1.shape)
display(df_commandes_q1.columns)
display(df_commandes_q1.info)

display(df_commandes_q2.shape)
display(df_commandes_q2.columns)
display(df_commandes_q2.info)

(3020, 10)

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison'],
      dtype='str')

<bound method DataFrame.info of        commande_id client_id produit_id  quantite  prix_unitaire  \
0     CMD-Q1-00001   CLI0496    PRD0081         1          49.36
1     CMD-Q1-00002   CLI0305    PRD0058         5         118.62
2     CMD-Q1-00003   CLI0044    PRD0128         7          99.94
3     CMD-Q1-00004   CLI0381    PRD0061         8          75.83
4     CMD-Q1-00005   CLI0187    PRD0040         4          71.91
...            ...       ...        ...       ...            ...
3015  CMD-Q1-02619   CLI0400    PRD0066         7         181.07
3016  CMD-Q1-01687   CLI0071    PRD0097         6         149.62
3017  CMD-Q1-01222   CLI0324    PRD0102         8          23.26
3018  CMD-Q1-02488   CLI0093    PRD0036         3         211.79
3019  CMD-Q1-01522   CLI0275    PRD0024         6          20.71

      montant_total date_commande    statut mode_paiement    region_livraison
0             49.36    2024-03-18   annulée            CB           Occitanie
1            593.10    2024-01-23    livrée            CB           Occitanie
2            699.58    2024-01-15    livrée        PayPal  Nouvelle-Aquitaine
3            606.64    2024-01-17   annulée        PayPal                PACA
4            287.64    2024-03-20  en_cours            CB           Occitanie
...             ...           ...       ...           ...                 ...
3015        1267.49    2024-03-14    livrée      Virement  Nouvelle-Aquitaine
3016         897.72    2024/02/16    livrée            CB         Auvergne-RA
3017         186.08    2024-02-06    livrée            CB           Occitanie
3018         635.37    2024-02-18    livrée            CB  Nouvelle-Aquitaine
3019         124.26    2024-02-15    livrée        PayPal       Île-de-France

[3020 rows x 10 columns]>

(3220, 11)

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'moyen_paiement',
       'region_livraison', 'devise'],
      dtype='str')

<bound method DataFrame.info of        commande_id client_id produit_id  quantite  prix_unitaire  \
0     CMD-Q2-00001   CLI0122    PRD0041         5          48.15
1     CMD-Q2-00002   CLI0346    PRD0106         1          52.42
2     CMD-Q2-00003   CLI0282    PRD0021         8          78.18
3     CMD-Q2-00004   CLI0292    PRD0141         9         326.57
4     CMD-Q2-00005   CLI0392    PRD0054         5         124.37
...            ...       ...        ...       ...            ...
3215  CMD-Q2-00605   CLI0341    PRD0095         8         106.83
3216  CMD-Q2-02643   CLI0493    PRD0076         9         211.08
3217  CMD-Q2-00511   CLI0428    PRD0081         6          49.36
3218  CMD-Q2-02836   CLI0085    PRD0126         1          82.76
3219  CMD-Q2-03170   CLI0122    PRD0120         5         107.93

      montant_total date_commande     statut moyen_paiement  \
0            240.75    2024-05-14  retournée             CB
1             52.42    2024-04-18     livrée             CB
2            625.44    2024-05-05    annulée             CB
3           2939.13    2024-05-31     livrée         Chèque
4            621.85    2024-06-27     livrée             CB
...             ...           ...        ...            ...
3215         854.64    2024-05-02  retournée             CB
3216        1899.72    2024-06-19   en_cours             CB
3217         296.16    2024-04-05     livrée             CB
3218          82.76    2024-05-14     livrée             CB
3219         539.65    2024-04-02     livrée         PayPal

        region_livraison devise
0            Auvergne-RA    EUR
1                   PACA    EUR
2              Occitanie    EUR
3              Occitanie    EUR
4            Auvergne-RA    EUR
...                  ...    ...
3215       Île-de-France    EUR
3216           Occitanie    EUR
3217           Occitanie    EUR
3218           Occitanie    EUR
3219  Nouvelle-Aquitaine    EUR

[3220 rows x 11 columns]>

### Ex E2 ⭐ — Détecter les différences entre Q1 et Q2
Trouvez les colonnes présentes dans Q2 mais absentes de Q1, et vice-versa.
Affichez les différences clairement.

In [2464]:
# TON CODE ICI
df_q1 = df_commandes_q1.columns
df_q2 = df_commandes_q2.columns
display(df_q1)
display(df_q2)
colonnes_q1  = df_q1.difference(df_q2)
colonnes_q2 = df_q2.difference(df_q1)
print("presente dans le q1 mais absente dans le q2")
display(colonnes_q1)
print("presente dans le q2 mais absente dans le q1")
display(colonnes_q2)

# colonnes_q1 = set(df_q1)
# colonnes_q2 = set(df_q2)

# print("Colonnes présentes dans Q2 mais absent++es de Q1 :")
# print(sorted(colonnes_q2 - colonnes_q1))

# print("Colonnes présentes dans Q1 mais absentes de Q2 :")
# print(sorted(colonnes_q1 - colonnes_q2))

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison'],
      dtype='str')

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'moyen_paiement',
       'region_livraison', 'devise'],
      dtype='str')

presente dans le q1 mais absente dans le q2

Index(['mode_paiement'], dtype='str')

presente dans le q2 mais absente dans le q1

Index(['devise', 'moyen_paiement'], dtype='str')

### Ex E3 ⭐ — Harmoniser les colonnes
1. Renommez la colonne problématique dans Q2 pour qu'elle corresponde à Q1
2. Ajoutez la colonne manquante dans Q1 avec une valeur par défaut
3. Vérifiez que les deux DataFrames ont maintenant les mêmes colonnes

In [2465]:
# TON CODE ICI
df_commandes_q2 = df_commandes_q2.rename(columns={"moyen_paiement": "mode_paiement"})
df_commandes_q2
df_commandes_q1["devise"] = "EUR"
df_commandes_q1
df_commandes_q2.columns == df_commandes_q1.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

### Ex E4 ⭐ — Consolider avec pd.concat
1. Ajoutez une colonne `source` dans Q1 (`'Q1_2024'`) et Q2 (`'Q2_2024'`)
2. Concaténez Q1 et Q2 avec `pd.concat`
3. Vérifiez que le total de lignes est cohérent
4. Affichez la répartition des lignes par source

In [2466]:
# TON CODE ICI
df_commandes_q1["source"] = "Q1_2024"
df_commandes_q2["source"] = "Q2_2024"

display(df_commandes_q1.head())
display(df_commandes_q2.head())
res_q1_q2 = pd.concat([df_commandes_q1,df_commandes_q2])
print(f"Q1: {len(df_commandes_q1)} + Q2: {len(df_commandes_q2) }= {len(res_q1_q2)}")
res_q1_q2["source"].value_counts()

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,EUR,Q1_2024
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,EUR,Q1_2024

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR,Q2_2024
1,CMD-Q2-00002,CLI0346,PRD0106,1,52.42,52.42,2024-04-18,livrée,CB,PACA,EUR,Q2_2024
2,CMD-Q2-00003,CLI0282,PRD0021,8,78.18,625.44,2024-05-05,annulée,CB,Occitanie,EUR,Q2_2024
3,CMD-Q2-00004,CLI0292,PRD0141,9,326.57,2939.13,2024-05-31,livrée,Chèque,Occitanie,EUR,Q2_2024
4,CMD-Q2-00005,CLI0392,PRD0054,5,124.37,621.85,2024-06-27,livrée,CB,Auvergne-RA,EUR,Q2_2024

Q1: 3020 + Q2: 3220= 6240

source
Q2_2024    3220
Q1_2024    3020
Name: count, dtype: int64

### Ex E5 ⭐⭐ — Fonction extract()
Encapsulez tout dans une fonction `extract(q1_path, q2_path, clients_path, produits_path) -> dict`
qui retourne un dictionnaire avec les 4 DataFrames harmonisés et consolidés.
La fonction doit afficher des logs à chaque étape.

In [2467]:
import logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(message)s", datefmt="%H:%M:%S")

logger = logging.getLogger("ETL")

In [2468]:
# TON CODE ICI
 

def extract(q1_path, q2_path, clients_path, produits_path) -> dict:
    print("début de l'extraction")
    df_q1 = pd.read_csv(q1_path)
    df_q1["source"] = "q1_2024"
    df_q2 = pd.read_csv(q2_path)
    df_q1["source"] = "q2_2024"

    df_clients = pd.read_csv(clients_path)
    df_produits = pd.read_csv(produits_path)

    print("harmoniser les colonnes")
    df_q2.rename(columns={"moyen_paiement": "mode_paiement"}, inplace=True)

    print("fusion des commandes")
    #librairie loggin
    all_commandes =pd.concat([df_q1,df_q2],ignore_index=True)

    print("remplacemant des devise manque par EUR")
    all_commandes["devise"] = all_commandes["devise"].fillna("EUR")
    display(all_commandes)
    

    print("Extraction terminer")
    


    print("retour d'un tableau Harmoniser et consolidés")
    return [all_commandes, df_clients, df_produits]
    


extract("data/commandes_Q1.csv", "data/commandes_Q2.csv", "data/clients.csv", "data/produits.csv")

début de l'extraction
harmoniser les colonnes
fusion des commandes
remplacemant des devise manque par EUR

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,source,devise
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,q2_2024,EUR
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,q2_2024,EUR
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,q2_2024,EUR
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,q2_2024,EUR
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,q2_2024,EUR
...,...,...,...,...,...,...,...,...,...,...,...,...
6235,CMD-Q2-00605,CLI0341,PRD0095,8,106.83,854.64,2024-05-02,retournée,CB,Île-de-France,NaN,EUR
6236,CMD-Q2-02643,CLI0493,PRD0076,9,211.08,1899.72,2024-06-19,en_cours,CB,Occitanie,NaN,EUR
6237,CMD-Q2-00511,CLI0428,PRD0081,6,49.36,296.16,2024-04-05,livrée,CB,Occitanie,NaN,EUR
6238,CMD-Q2-02836,CLI0085,PRD0126,1,82.76,82.76,2024-05-14,livrée,CB,Occitanie,NaN,EUR
6239,CMD-Q2-03170,CLI0122,PRD0120,5,107.93,539.65,2024-04-02,livrée,PayPal,Nouvelle-Aquitaine,NaN,EUR

Extraction terminer
retour d'un tableau Harmoniser et consolidés

[       commande_id client_id produit_id  quantite  prix_unitaire  \
 0     CMD-Q1-00001   CLI0496    PRD0081         1          49.36
 1     CMD-Q1-00002   CLI0305    PRD0058         5         118.62
 2     CMD-Q1-00003   CLI0044    PRD0128         7          99.94
 3     CMD-Q1-00004   CLI0381    PRD0061         8          75.83
 4     CMD-Q1-00005   CLI0187    PRD0040         4          71.91
 ...            ...       ...        ...       ...            ...
 6235  CMD-Q2-00605   CLI0341    PRD0095         8         106.83
 6236  CMD-Q2-02643   CLI0493    PRD0076         9         211.08
 6237  CMD-Q2-00511   CLI0428    PRD0081         6          49.36
 6238  CMD-Q2-02836   CLI0085    PRD0126         1          82.76
 6239  CMD-Q2-03170   CLI0122    PRD0120         5         107.93

       montant_total date_commande     statut mode_paiement  \
 0             49.36    2024-03-18    annulée            CB
 1            593.10    2024-01-23     livrée            CB
 2            699.58    2024-01-15     livrée        PayPal
 3            606.64    2024-01-17    annulée        PayPal
 4            287.64    2024-03-20   en_cours            CB
 ...             ...           ...        ...           ...
 6235         854.64    2024-05-02  retournée            CB
 6236        1899.72    2024-06-19   en_cours            CB
 6237         296.16    2024-04-05     livrée            CB
 6238          82.76    2024-05-14     livrée            CB
 6239         539.65    2024-04-02     livrée        PayPal

         region_livraison   source devise
 0              Occitanie  q2_2024    EUR
 1              Occitanie  q2_2024    EUR
 2     Nouvelle-Aquitaine  q2_2024    EUR
 3                   PACA  q2_2024    EUR
 4              Occitanie  q2_2024    EUR
 ...                  ...      ...    ...
 6235       Île-de-France      NaN    EUR
 6236           Occitanie      NaN    EUR
 6237           Occitanie      NaN    EUR
 6238           Occitanie      NaN    EUR
 6239  Nouvelle-Aquitaine      NaN    EUR

 [6240 rows x 12 columns],
     client_id         nom               email      ville              region  \
 0     CLI0001    Client_1    client1@email.fr   Toulouse         Auvergne-RA
 1     CLI0002    Client_2    client2@email.fr       Lyon  Nouvelle-Aquitaine
 2     CLI0003    Client_3    client3@email.fr     Nantes           Occitanie
 3     CLI0004    Client_4    client4@email.fr     Nantes                PACA
 4     CLI0005    Client_5    client5@email.fr      Paris       Île-de-France
 ..        ...         ...                 ...        ...                 ...
 510   CLI0173  Client_173  client173@email.fr   Toulouse       Île-de-France
 511   CLI0248  Client_248  client248@email.fr  Marseille         Auvergne-RA
 512   CLI0198  Client_198  client198@email.fr      Paris  Nouvelle-Aquitaine
 513   CLI0033   Client_33   client33@email.fr     Nantes                PACA
 514   CLI0163  Client_163  client163@email.fr     Nantes  Nouvelle-Aquitaine

           segment date_inscription  ca_historique  actif
 0         Startup       2021-02-01         129.67   True
 1     Particulier       2022-08-11       42431.54  False
 2             PME       2023-11-17        6895.77   True
 3     Particulier       2023-10-20       11034.84   True
 4     Particulier       2022-12-29        2331.35  False
 ..            ...              ...            ...    ...
 510           PME       2023-05-28        4982.27   True
 511           PME       2022-04-01         456.98  False
 512  Grand Compte       2021-05-31        1025.62  False
 513       Startup       2020-12-02       10689.65   True
 514           PME       2023-02-04       10621.32   True

 [515 rows x 9 columns],
     produit_id              nom     categorie  prix_unitaire  stock  \
 0      PRD0001    Produit_Inf_1  Informatique          57.96     71
 1      PRD0002    Produit_Inf_2  Informatique         135.96    102
 2      PRD0003    Produit_Inf_3  Informatique          83.45    372
 3      PRD0004    Produit_Inf_4  Informatique          42.82    151
 4      PRD0005    Produit_Inf_5  Informatique          95.95    413
 ..         ...              ...           ...            ...    ...
 147    PRD0148  Produit_Rés_148        Réseau          70.91    232
 148    PRD0149  Produit_Rés_149        Réseau         123.18    222
 149    PRD0150  Produit_Rés_150        Réseau          81.48    338
 150    PRD0151  Produit_Rés_151        Réseau         221.15    468
 151    PRD0152  Produit_Rés_152        Réseau         499.98    150

     fournisseur  actif
 0       TechPro   True
 1     MediaShop   True
 2      ElecPlus  False
 3     DataStore   True
 4     MediaShop   True
 ..          ...    ...
 147   DataStore  False
 148    ElecPlus  False
 149   MediaShop   True
 150    ElecPlus   True
 151    ElecPlus   True

 [152 rows x 7 columns]]

---
# 🟡 PARTIE TRANSFORM

### Ex T1 ⭐ — Audit initial
Écris une fonction `audit_dataframe(df, nom)` qui affiche :
- Shape
- Nombre de NaN total et par colonne (en %)
- Nombre de doublons
- Types de chaque colonne

In [2469]:
# TON CODE ICI
def audit_dataframe(df,nom):
    print(type(df))
    print("#=======================================#")
    display("Nom :", nom)
    display("Shape :",df.shape)
    print("#=======================================#")
    display("Nombre de NaN et par colonne en % :")
    print(df.isna().sum() / len(df))
    print("#=======================================#")
    print("Nombre de doublons :")
    print(df.duplicated().sum())
    print("#=======================================#")
    print("Types de chaque colonne :")
    print(df.dtypes)


audit_dataframe(df_clients,"clients")
audit_dataframe(df_produits,"produit")
audit_dataframe(df_commandes_q1,"commande_q1")
audit_dataframe(df_commandes_q2,"commande_q2")

<class 'pandas.DataFrame'>
#=======================================#

'Nom :'

'clients'

'Shape :'

(515, 9)

#=======================================#

'Nombre de NaN et par colonne en % :'

client_id           0.000000
nom                 0.000000
email               0.060194
ville               0.000000
region              0.000000
segment             0.000000
date_inscription    0.000000
ca_historique       0.000000
actif               0.000000
dtype: float64
#=======================================#
Nombre de doublons :
15
#=======================================#
Types de chaque colonne :
client_id               str
nom                     str
email                   str
ville                   str
region                  str
segment                 str
date_inscription        str
ca_historique       float64
actif                  bool
dtype: object
<class 'pandas.DataFrame'>
#=======================================#

'Nom :'

'produit'

'Shape :'

(152, 7)

#=======================================#

'Nombre de NaN et par colonne en % :'

produit_id       0.0
nom              0.0
categorie        0.0
prix_unitaire    0.0
stock            0.0
fournisseur      0.0
actif            0.0
dtype: float64
#=======================================#
Nombre de doublons :
0
#=======================================#
Types de chaque colonne :
produit_id           str
nom                  str
categorie            str
prix_unitaire    float64
stock              int64
fournisseur          str
actif               bool
dtype: object
<class 'pandas.DataFrame'>
#=======================================#

'Nom :'

'commande_q1'

'Shape :'

(3020, 12)

#=======================================#

'Nombre de NaN et par colonne en % :'

commande_id         0.000000
client_id           0.000000
produit_id          0.000000
quantite            0.000000
prix_unitaire       0.000000
montant_total       0.018543
date_commande       0.000000
statut              0.010265
mode_paiement       0.000000
region_livraison    0.000000
devise              0.000000
source              0.000000
dtype: float64
#=======================================#
Nombre de doublons :
20
#=======================================#
Types de chaque colonne :
commande_id             str
client_id               str
produit_id              str
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande           str
statut                  str
mode_paiement           str
region_livraison        str
devise                  str
source                  str
dtype: object
<class 'pandas.DataFrame'>
#=======================================#

'Nom :'

'commande_q2'

'Shape :'

(3220, 12)

#=======================================#

'Nombre de NaN et par colonne en % :'

commande_id         0.000000
client_id           0.000000
produit_id          0.000000
quantite            0.000000
prix_unitaire       0.000000
montant_total       0.018944
date_commande       0.000000
statut              0.009627
mode_paiement       0.000000
region_livraison    0.000000
devise              0.000000
source              0.000000
dtype: float64
#=======================================#
Nombre de doublons :
20
#=======================================#
Types de chaque colonne :
commande_id             str
client_id               str
produit_id              str
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande           str
statut                  str
mode_paiement           str
region_livraison        str
devise                  str
source                  str
dtype: object

### Ex T2 ⭐ — Supprimer les doublons
Sur le DataFrame consolidé :
1. Détectez et affichez le nombre de doublons
2. Montrez 3 exemples de lignes dupliquées
3. Supprimez les doublons (gardez la première occurrence)
4. Vérifiez qu'il n'en reste plus

In [2470]:
# TON CODE ICI

print("nombre de doublons dans res_q1_q2")
display(res_q1_q2.duplicated().sum())
print("3 example de ligne dupliquées")
display(res_q1_q2[res_q1_q2.duplicated(keep=False)].sort_values(by="commande_id").head(3))
print("supprition des doublons et garder le premier occurances")
res_q1_q2  = res_q1_q2.drop_duplicates(keep='first')
print("verifier qu'il n'en reste plus")
display(res_q1_q2.duplicated().sum())

nombre de doublons dans res_q1_q2

np.int64(40)

3 example de ligne dupliquées

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
13,CMD-Q1-00014,CLI0208,PRD0090,5,80.66,403.30,2024-02-05,livrée,CB,Nouvelle-Aquitaine,EUR,Q1_2024
3009,CMD-Q1-00014,CLI0208,PRD0090,5,80.66,403.30,2024-02-05,livrée,CB,Nouvelle-Aquitaine,EUR,Q1_2024
3001,CMD-Q1-00072,CLI0001,PRD0027,7,45.84,320.88,2024-03-20,en_cours,CB,Île-de-France,EUR,Q1_2024

supprition des doublons et garder le premier occurances
verifier qu'il n'en reste plus

np.int64(0)

### Ex T3 ⭐ — Corriger les types
1. Convertissez `date_commande` en datetime en gérant les formats incohérents
2. Extrayez : `annee`, `mois`, `trimestre`, `jour_semaine`
3. Convertissez `quantite` en numérique avec gestion des erreurs
4. Affichez les types avant et après

In [2471]:
# # TON CODE ICI
print("Avant :")
print(res_q1_q2.dtypes)
print("==================date time & format incoherant ====================")
res_q1_q2["date_commande"]= pd.to_datetime(res_q1_q2["date_commande"], format="mixed", errors="coerce")

res_q1_q2["annee"] = res_q1_q2["date_commande"].dt.year
res_q1_q2["mois"] = res_q1_q2["date_commande"].dt.month
res_q1_q2["trimestre"] = res_q1_q2["date_commande"].dt.quarter
res_q1_q2["jour_semaine"] = res_q1_q2["date_commande"].dt.day_name()

res_q1_q2["quantite"] = pd.to_numeric(res_q1_q2["quantite"],errors="coerce")


print("apres :")
display(res_q1_q2.dtypes)
res_q1_q2

Avant :
commande_id             str
client_id               str
produit_id              str
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande           str
statut                  str
mode_paiement           str
region_livraison        str
devise                  str
source                  str
dtype: object
==================date time & format incoherant ====================
apres :

commande_id                    str
client_id                      str
produit_id                     str
quantite                     int64
prix_unitaire              float64
montant_total              float64
date_commande       datetime64[us]
statut                         str
mode_paiement                  str
region_livraison               str
devise                         str
source                         str
annee                        int32
mois                         int32
trimestre                    int32
jour_semaine                   str
dtype: object

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source,annee,mois,trimestre,jour_semaine
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024,2024,3,1,Monday
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024,2024,1,1,Tuesday
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024,2024,1,1,Monday
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,EUR,Q1_2024,2024,1,1,Wednesday
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,EUR,Q1_2024,2024,3,1,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,CMD-Q2-03196,CLI0454,PRD0127,1,63.31,63.31,2024-06-09,livrée,PayPal,Auvergne-RA,EUR,Q2_2024,2024,6,2,Sunday
3196,CMD-Q2-03197,CLI0222,PRD0054,5,124.37,621.85,2024-06-10,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q2_2024,2024,6,2,Monday
3197,CMD-Q2-03198,CLI0030,PRD0135,3,112.71,338.13,2024-05-06,livrée,CB,Nouvelle-Aquitaine,EUR,Q2_2024,2024,5,2,Monday
3198,CMD-Q2-03199,CLI0187,PRD0091,7,75.28,526.96,2024-05-21,livrée,CB,Nouvelle-Aquitaine,EUR,Q2_2024,2024,5,2,Tuesday
3199,CMD-Q2-03200,CLI0434,PRD0059,8,117.97,943.76,2024-06-25,livrée,CB,PACA,EUR,Q2_2024,2024,6,2,Tuesday

### Ex T4 ⭐⭐ — Traiter les NaN
Pour chaque colonne avec des NaN, choisissez et appliquez la stratégie adaptée :
- `montant_total` NaN → recalculer depuis `quantite × prix_unitaire`
- `statut` NaN → valeur par défaut `'inconnu'`
- `date_commande` NaT → supprimer la ligne (donnée critique)

Justifiez chaque choix dans un commentaire.

In [2472]:
# TON CODE ICI
display(res_q1_q2["montant_total"].isna().value_counts())
res_q1_q2 = res_q1_q2.reset_index(drop=True)
res_q1_q2.loc[res_q1_q2["montant_total"].isna(),"montant_total"]= res_q1_q2["quantite"] * res_q1_q2["prix_unitaire"]
res_q1_q2.index.is_unique
display(res_q1_q2["montant_total"].isna().value_counts())

display(res_q1_q2["statut"].isna().value_counts())
# Pour les status de valeur nan on remplace par 'inconnu'
res_q1_q2.loc[res_q1_q2["statut"].isna(),"statut"] = "inconnu"
display(res_q1_q2["statut"].isna().value_counts())

print("===================supprimer mes nat ===================")
res_q1_q2 = res_q1_q2.dropna(subset=["date_commande"])

display(res_q1_q2["date_commande"].isnull().value_counts())
display(res_q1_q2["date_commande"].isna().value_counts())

montant_total
False    6083
True      117
Name: count, dtype: int64

montant_total
False    6200
Name: count, dtype: int64

statut
False    6138
True       62
Name: count, dtype: int64

statut
False    6200
Name: count, dtype: int64

===================supprimer mes nat ===================

date_commande
False    6200
Name: count, dtype: int64

date_commande
False    6200
Name: count, dtype: int64

### Ex T5 ⭐⭐ — Détecter et traiter les aberrants
1. Détectez les prix négatifs → supprimez ces lignes
2. Détectez les quantités nulles ou négatives → supprimez
3. Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences
4. Affichez un résumé des corrections effectuées

In [2473]:

print("3. verifier la coherance de  'montant_total'")
df_diff = res_q1_q2["montant_total"] != (
    res_q1_q2["quantite"] * res_q1_q2["prix_unitaire"])
nb_montants_corriges = df_diff.sum()
print(df_diff[df_diff == True].value_counts().sum())
#correction de valeur incoherante
res_q1_q2.loc[df_diff,'montant_total']= res_q1_q2["prix_unitaire"] * res_q1_q2["quantite"]
df_diff_after = res_q1_q2["montant_total"] != (
    res_q1_q2["quantite"] * res_q1_q2["prix_unitaire"]
)
print(df_diff_after[df_diff_after == True].value_counts().sum())

3. verifier la coherance de  'montant_total'
920
0

In [2474]:
# TON CODE ICI
# prix négatifs et supprimer les lignes des prix négatifs
res_q1_q2_px_negatif = res_q1_q2[res_q1_q2["prix_unitaire"] < 0]
print(res_q1_q2_px_negatif["prix_unitaire"].value_counts().sum())
res_q1_q2 = res_q1_q2.drop(res_q1_q2_px_negatif.index) 
display(res_q1_q2[res_q1_q2["prix_unitaire"] < 0].value_counts().sum())

#detectez les quantités 
res_q1_quantite_null_negatif =  df_commandes_q1["quantite"] <= 0
print(f"nombre de null ou négatifs dans commande_q1 : {res_q1_quantite_null_negatif.sum()}")
res_q2_quantite_null_negatif =  df_commandes_q2["quantite"] <= 0
print(f"nombre de null ou négatifs dans commande_q2 : {res_q2_quantite_null_negatif.sum()}")
#resultat des negative commandes q1 et q2 nb total
display(f"total des valeurs des negatif et null entre commande q1 plus ceux de comande q2 {res_q1_quantite_null_negatif.sum() + res_q2_quantite_null_negatif.sum()}")



res_q1_q2_quantite_null_negatif =  ((res_q1_q2["quantite"] <= 0) | (res_q1_q2["quantite"].isnull()))

nb_quantites_ivalides =res_q1_q2_quantite_null_negatif[res_q1_q2_quantite_null_negatif == True].value_counts().sum()
display("valuer null ou négative avant suppression : ",res_q1_q2_quantite_null_negatif[res_q1_q2_quantite_null_negatif == True].value_counts().sum())
res_q1_q2 = res_q1_q2.drop(res_q1_q2[res_q1_q2_quantite_null_negatif].index)
display("valuer null ou négative apres suppression : ",res_q1_q2[res_q1_q2["quantite"] <= 0].value_counts().sum())



print("3. verifier la coherance de  'montant_total'")
df_diff = res_q1_q2["montant_total"] != (
    res_q1_q2["quantite"] * res_q1_q2["prix_unitaire"]
)
print(df_diff[df_diff == True].value_counts().sum())
#correction de valeur incoherante
res_q1_q2.loc[df_diff,'montant_total']= res_q1_q2["prix_unitaire"] * res_q1_q2["quantite"]
df_diff_after = res_q1_q2["montant_total"] != (
    res_q1_q2["quantite"] * res_q1_q2["prix_unitaire"]
)
# on trouve zero car les incoherance venais des valeurs negatifs ou nulls c'est pour quil plus de valeur incohérante
print(df_diff_after[df_diff_after == True].value_counts().sum())

22

np.int64(0)

nombre de null ou négatifs dans commande_q1 : 12
nombre de null ou négatifs dans commande_q2 : 19

'total des valeurs des negatif et null entre commande q1 plus ceux de comande q2 31'

'valuer null ou négative avant suppression : '

np.int64(29)

'valuer null ou négative apres suppression : '

np.int64(0)

3. verifier la coherance de  'montant_total'
0
0

In [2475]:
print("Resumer des corrections :")
print(f"- Prix négatifs supprimés: {len(res_q1_q2_quantite_null_negatif)}")
print(f"- Quantités nul ou négatives supprimer : {nb_quantites_ivalides}")
print(f"- Montants totaux corrigés : {nb_montants_corriges}")

Resumer des corrections :
- Prix négatifs supprimés: 6178
- Quantités nul ou négatives supprimer : 29
- Montants totaux corrigés : 920

### Ex T6 ⭐⭐ — Jointures avec les référentiels
1. Nettoyez `df_clients` (doublons sur `client_id`)
2. Filtrez `df_produits` pour ne garder que les produits actifs
3. Faites un LEFT JOIN commandes ← clients (colonnes : ville, region, segment)
4. Faites un LEFT JOIN commandes ← produits (colonnes : nom, categorie, fournisseur)
5. Vérifiez le nombre de lignes avant et après (doit être identique avec LEFT JOIN)

In [2476]:
# TON CODE ICI
#Nettoyage df_clients  doublons sur client_id
print("Nettoyage df_clients  doublons sur client_id")
display(f"nombre de doublons de client_id :  {df_clients.duplicated(subset="client_id").sum()}")
df_clients = df_clients.drop_duplicates(subset="client_id")
display(f"nombre de doublons de client_id aprés le nettoyage :  {df_clients.duplicated(subset="client_id").sum()}")

#2. filtrer les produits pour garder les produits actifs
print("filtre les produis actifs")
produits_inactif = df_produits[df_produits["actif"] == False]
display(f"nombres de produits inactifs :  {produits_inactif.value_counts().sum()}")
df_produits = df_produits.drop(produits_inactif.index)
display(f"nombres de produits inactifs : {df_produits[df_produits["actif"]==False].value_counts().sum()}")


#3. left join commande et client
print("3. left join commande a clients")
df_resultat_cmd_clt = res_q1_q2.merge(
    df_clients,
    on="client_id",
    how="left"
)
display(df_resultat_cmd_clt.head(1))

#left join commande et produits
print("4. left join commande a produits")
df_resultat_cmd_prd = res_q1_q2.merge(
    df_produits,
    on="produit_id",
    how="left"
)
display(df_resultat_cmd_prd.head(1))

print("5. verifier le nombre de ligne avant et aprés les left join")
display(df_produits.shape)

display(df_resultat_cmd_clt.shape)
display(df_resultat_cmd_prd.shape)

Nettoyage df_clients  doublons sur client_id

'nombre de doublons de client_id :  15'

'nombre de doublons de client_id aprés le nettoyage :  0'

filtre les produis actifs

'nombres de produits inactifs :  45'

'nombres de produits inactifs : 0'

3. left join commande a clients

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,...,trimestre,jour_semaine,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,...,1,Monday,Client_496,client496@email.fr,Marseille,PACA,Particulier,2021-07-26,14294.54,True

4. left join commande a produits

,commande_id,client_id,produit_id,quantite,prix_unitaire_x,montant_total,date_commande,statut,mode_paiement,region_livraison,...,annee,mois,trimestre,jour_semaine,nom,categorie,prix_unitaire_y,stock,fournisseur,actif
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,...,2024,3,1,Monday,NaN,NaN,NaN,NaN,NaN,NaN

5. verifier le nombre de ligne avant et aprés les left join

(107, 7)

(6149, 24)

(6149, 22)

### Ex T7 ⭐⭐ — Feature Engineering
Créez les colonnes suivantes :
1. `tranche_montant` : `<100€` / `100-500€` / `500-2000€` / `>2000€` avec `pd.cut()`
2. `saison` : depuis le mois (Hiver/Printemps/Été/Automne)
3. `est_annulee` : booléen True si statut == 'annulée'
4. `ca_perdu` : montant_total si commande annulée, sinon 0
5. `delai_inscription_commande` : nb de jours entre date_inscription du client et date_commande

Affichez `value_counts()` pour les colonnes catégorielles créées.

In [2477]:
# TON CODE ICI
#1. tranche_montant
df_resultat_cmd_clt["tranche_montant"] = pd.cut(res_q1_q2["montant_total"],  bins=[-float("inf"),100, 500,2000, float("inf")], labels=[  "<100€",
    "100-500€",
    "500-2000€",
    ">2000€"])
display(df_resultat_cmd_clt["tranche_montant"].value_counts())

# help(pd.cut)
#2. saison 
def saison(mois):
    if  mois in [12,1,2]:
        return 'hiver'
    elif 3 <= mois <= 5:
        return 'printemps'
    elif 5 < mois <= 8:
        return "été"
    elif 8 < mois <= 11:
        return "automne"
    else :
        return "erreur de valeur"

df_resultat_cmd_clt["saison"] = df_resultat_cmd_clt["mois"].apply(saison)
df_resultat_cmd_clt.head(4)

#3.est annulee
df_resultat_cmd_clt["statut"].head()
df_resultat_cmd_clt["est_annulee"] =df_resultat_cmd_clt["statut"] == "annulée"
#4. ca_perdu
df_resultat_cmd_clt["ca_perdu"] = 0.0
df_resultat_cmd_clt.loc[df_resultat_cmd_clt["est_annulee"]==True,["ca_perdu"]] = df_resultat_cmd_clt["montant_total"]
df_resultat_cmd_clt.head(2)

#5. delai inscription
df_resultat_cmd_clt[["date_commande","date_inscription"]].dtypes
df_resultat_cmd_clt["date_inscription"] = pd.to_datetime(df_resultat_cmd_clt["date_inscription"], format="mixed")
df_resultat_cmd_clt["delai_inscription_commande"] = df_resultat_cmd_clt["date_commande"] - df_resultat_cmd_clt["date_inscription"]
df_resultat_cmd_clt["saison"] = df_resultat_cmd_clt["mois"].apply(saison)

#afficher les  value_count() des cateories
print(df_resultat_cmd_clt["tranche_montant"].value_counts())
print(df_resultat_cmd_clt["saison"].value_counts())
print(df_resultat_cmd_clt["est_annulee"].value_counts())
print(df_resultat_cmd_clt["ca_perdu"].value_counts())
print(df_resultat_cmd_clt["delai_inscription_commande"].value_counts())

tranche_montant
100-500€     2930
500-2000€    2150
<100€         638
>2000€        381
Name: count, dtype: int64

tranche_montant
100-500€     2930
500-2000€    2150
<100€         638
>2000€        381
Name: count, dtype: int64
saison
printemps    3096
hiver        2006
été          1047
Name: count, dtype: int64
est_annulee
False    5544
True      605
Name: count, dtype: int64
ca_perdu
0.00       5544
878.52        4
863.44        4
392.22        4
372.76        4
           ...
167.61        1
2620.03       1
1139.13       1
336.96        1
165.09        1
Name: count, Length: 481, dtype: int64
delai_inscription_commande
528 days     15
640 days     12
1019 days    11
490 days     11
1046 days    11
             ..
525 days      1
498 days      1
1443 days     1
1571 days     1
1472 days     1
Name: count, Length: 1546, dtype: int64

### Ex T8 ⭐⭐⭐ — Validation qualité
Écris une fonction `valider_pipeline(df) -> bool` qui :
1. Vérifie qu'il n'y a plus de NaN sur les colonnes critiques
2. Vérifie qu'il n'y a plus de doublons
3. Vérifie que tous les prix sont > 0
4. Vérifie que toutes les quantités sont > 0
5. Vérifie que montant_total == quantite × prix_unitaire (à 1 centime près)
6. Retourne True si tout est OK, False sinon avec les erreurs détaillées

In [2478]:
# TON CODE ICI
def valider_pipeline(df) -> bool:
    #1. vérifie plus de nan sur les colonnes critiques
    erreur = []
    df_critique_nan = df[["client_id","commande_id","produit_id","montant_total","quantite","date_commande", "prix_unitaire",]].isna().sum()

    for  colonne, valeur in df_critique_nan.items():
        if valeur > 0:
            erreur.append(f"{colonne}: {valeur}")
    
    #2. doublons
    s = df.duplicated().sum()
    print(s)
    if s > 0:
        erreur.append(s)
        display(f"il y' a {erreur} de doulons")
    
    #3. prix > 0
    df_supp_zero = df["prix_unitaire"].sum()
    if df_supp_zero <= 0 :
        print(f"prix inferieur a zero : {df["prix_unitaire"]}")
        erreur.append(f"prix inferreur a zero {df_supp_zero}")
    elif df_supp_zero > 0:
        print("aucun prix inferieur a Zéro")
    else:
        print("une erreur de prix 'valeur' non conforme")

    #4. quantite > 0 
    df_supp_quantite  = df["quantite"].sum()
    if df_supp_quantite <= 0 :
        print(f"quantite inferieur a zero : {df["quantite"]}")
        erreur.append(f"quantite inferreur a zero {df_supp_quantite}")
    elif df_supp_quantite > 0:
        print("aucun quantite inferieur a Zéro")
    else:
        print("une erreur de quantite 'valeur' non conforme")

    #5. verifiez montant_total = quantite * prix_unitaire
    df_cal_prix = df["prix_unitaire"].round(2) * df["quantite"]
    ecart = df["montant_total"].round(2) - df_cal_prix.round(2)
    if ((ecart > 0.01) | (ecart < -0.01)).any():
        erreur.append(f"le prix et superieur ou inferieur a {ecart}")
        print("le prix est inferieur au critere ou supperieur au centimes pret")
    else:
        print("le prix corespond au centimes pret")
    
    if erreur  :
        print(f"eurreur {erreur}")
        return False

    logger.info("Pipline valine aucune erreur a etait detecter")
    return True 

valider_pipeline(df_resultat_cmd_clt)

15:08:40 | Pipline valine aucune erreur a etait detecter

0
aucun prix inferieur a Zéro
aucun quantite inferieur a Zéro
le prix corespond au centimes pret

True

### Ex T9 ⭐⭐⭐ — Analyse métier post-transform
Maintenant que les données sont propres, répondez en code :
1. Quel est le CA total du S1 2024 ?
2. Quel trimestre a le CA le plus élevé ?
3. Quelle région génère le plus de CA ?
4. Quel segment client est le plus rentable ?
5. Quelle catégorie de produit a le taux d'annulation le plus élevé ?
6. Quel est le CA perdu sur les annulations ?

In [2479]:
# TON CODE ICI

---
# 🔵 PARTIE LOAD

### Ex L1 ⭐ — Export CSV
1. Exportez le DataFrame enrichi en CSV dans `../output/commandes_enrichies.csv`
2. Vérifiez la taille du fichier en Ko
3. Rechargez le CSV et vérifiez que le shape est identique

In [2480]:
# TON CODE ICI

### Ex L2 ⭐⭐ — Export Parquet
1. Exportez en Parquet dans `../output/commandes_S1.parquet`
2. Comparez la taille CSV vs Parquet
3. Rechargez le Parquet et vérifiez le shape
4. Mesurez le temps de lecture CSV vs Parquet avec `%%time`

In [2481]:
# TON CODE ICI

### Ex L3 ⭐⭐ — SQLite
1. Créez une base SQLite `../output/ecommerce.db`
2. Chargez le DataFrame dans une table `commandes`
3. Créez une deuxième table `reporting` avec un agrégat par trimestre et région
4. Exécutez au moins 3 requêtes SQL directement depuis Python et affichez les résultats

In [2482]:
# TON CODE ICI

### Ex L4 ⭐⭐⭐ — Parquet partitionné
Exportez le DataFrame en Parquet partitionné par `trimestre` et `region_livraison`.

Puis répondez :
- Combien de fichiers Parquet sont créés ?
- Quelle est la taille totale vs le Parquet non partitionné ?
- Quel est l'avantage du partitionnement pour PySpark ?

In [2483]:
# TON CODE ICI

---
# 🔴 PIPELINE COMPLET

### Ex P1 ⭐⭐ — Pipeline modulaire
Écris 3 fonctions séparées :
- `extract(data_dir) -> dict`
- `transform(sources: dict) -> pd.DataFrame`
- `load(df, output_dir) -> None`

Chacune doit avoir une docstring et des logs.
Teste chaque fonction indépendamment.

In [2484]:
# TON CODE ICI

### Ex P2 ⭐⭐⭐ — Pipeline avec gestion d'erreurs
Améliore ton pipeline avec :
1. `try/except` sur chaque étape critique
2. Un log d'erreur détaillé si une étape échoue
3. La pipeline ne doit pas crasher complètement si un fichier est manquant — elle doit logger l'erreur et continuer avec les autres

In [2485]:
# TON CODE ICI

### Ex P3 ⭐⭐⭐ — Tests unitaires du pipeline
Écris 5 tests pour ton pipeline :
1. `test_extract_retourne_4_sources()`
2. `test_transform_supprime_doublons()`
3. `test_transform_pas_de_prix_negatif()`
4. `test_transform_montant_coherent()`
5. `test_load_cree_les_fichiers()`

Chaque test affiche ✅ PASS ou ❌ FAIL.

In [2486]:
# TON CODE ICI

### Ex P4 ⭐⭐⭐⭐ — PROJET FINAL : Pipeline automatisé
Crée un pipeline complet qui :

1. **Détecte automatiquement** tous les fichiers CSV dans `../data_etl/` qui commencent par `commandes_`
2. **Les traite tous** sans avoir à spécifier les chemins manuellement
3. **Génère un rapport HTML** avec :
   - Les statistiques clés (CA, nb commandes, taux annulation)
   - 3 graphiques Plotly intégrés
4. **Sauvegarde** en CSV + Parquet + SQLite
5. **Loggue** chaque étape avec timestamps

C'est exactement ce que vous ferez en PySpark la semaine prochaine, mais à l'échelle de plusieurs To.

📎 Docs utiles :
- [glob — trouver des fichiers](https://docs.python.org/3/library/glob.html)
- [logging](https://docs.python.org/3/library/logging.html)
- [Plotly — export HTML](https://plotly.com/python/interactive-html-export/)

In [2487]:
# TON CODE ICI